services:
  db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/s3cr3t
    healthcheck:
      test: "exit 0"
    volumes:
      - /home/ane/neo4j/Tareas-Adicionales/Volumenes/data:/data
      - /home/ane/neo4j/Tareas-Adicionales/Volumenes/logs:/logs
  cliente-neo4j:
    container_name: neo4j-cliente-python
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ["Marcos", "Merino", "Hugo", "Robles"]
