services:
  db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/s3cr3t
    healthcheck:
      test: "exit 0"
    volumes:
      - /home/ane/neo4j/Tareas-Adicionales/TerceraAplicacion/data:/data
      - /home/ane/neo4j/Tareas-Adicionales/TerceraAplicacion/code/logs:/logs
  cliente-neo4j:
    container_name: neo4j-cliente-python
    build: .
    volumes:
      - /home/ane/neo4j/Tareas-Adicionales/TerceraAplicacion/code:/code
    depends_on:
      db:
        condition: service_healthy
    command: ["B", "B", "A", "A", "R"]
  cliente-web:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - ./code:/usr/local/apache2/htdocs
    depends_on:
      db:
        condition: service_healthy
