apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bd
  template:
    metadata:
      labels:
        component: bd
    spec:
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: mi-reclamacion-vp
      containers:
      - name: mi-pod-bd
        image: neo4j
        env:
          - name: NEO4J_AUTH
            value: "neo4j/s3cr3t"
        ports:
        - containerPort: 7474
        - containerPort: 7687
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
