apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bd
  template:
    metadata:
      labels:
        component: bd
    spec:
      containers:
      - name: mi-pod-bd
        image: neo4j
        ports:
        - containerPort: 7474
        - containerPort: 7687