apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-neo4j
  labels:
    app: neo4j-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-cli
  template:
    metadata:
      labels:
        app: neo4j-cli
  spec:
    containers:
      - name: neo4j-bd
        image: neo4j
        ports:
          - containerPort: 7474
            name: browser
          - containerPort: 7687
            name: bolt
        environment:
          NEO4J_AUTH: neo4j/s3cr3t
        healthcheck:
          test: "exit 0"
      - name: cliente
        build: .
        depends_on:
          db:
            condition: service_healthy
        command: ["Ane", "Garcia", "Alba", "Reche"]
