apiVersion: v1
kind: Service
metadata:
  name: mi-load-balancer
  labels:
    component: bd
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
  selector:
    component: bd
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127