apiVersion: v1
kind: Service
metadata:
  name: mi-service
  labels:
    component: bd
spec:
  selector:
    component: bd
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687

status:
  loadBalancer:
    ingress:
    - ip: 34.105.142.5